### ISSUE TITLE
pybullet out of date in 

### ISSUE THREAD

**Issue by ThorAvaTahr** [axelbr/racecar_gym#11]
doesn't work out of the box:

I get the following error
importerror numpy.core.multiarray failed to import

I am on windows using pycharm

fixed after updating pybullet to latest version

**Comment by axelbr** [comment]
I just tried to do a fresh install with `pip install -e .` but I could not reproduce your error. Can you provide a set of commands that reproduce this error in a fresh python 3.10 virtual environment?

**Comment by axelbr** [comment]
i will close this for now. feel free to reopen if this error persists.
