### ISSUE TITLE
Feature request: migrate from gym to gymnasium

### ISSUE THREAD

**Issue by elliottower** [axelbr/racecar_gym#12]
Hi, this repository is currently listed in the gymnasium [third party environments](https://gymnasium.farama.org/environments/third_party_environments/) but we are cleaning the list up to only include maintained gymnasium-compatible repositories.  

Would it be possible for it to be upgraded from gym to gymnasium? [Gymnasium](https://github.com/Farama-Foundation/Gymnasium) is the maintained version of openai gym and is compatible with current RL training libraries ([rllib](https://github.com/ray-project/ray/tree/master/rllib) and [tianshou](https://github.com/thu-ml/tianshou) have already migrated, and [stable-baselines3](https://github.com/DLR-RM/stable-baselines3/blob/e5deeed16efb57c34ccdcb14692439154d970527/docs/guide/install.rst#bleeding-edge-version) will soon).  

For information about upgrading and compatibility, see [migration guide](https://gymnasium.farama.org/content/migration-guide/) and [gym compatibility](https://gymnasium.farama.org/content/gym_compatibility/). The main difference is the API has switched to returning `truncated` and `terminated`, rather than `done`, in order to give more information and mitigate edge case issues.

**Comment by axelbr** [comment]
Hi!
Thanks for the reminder. We will migrate to gymnasium soon (possibly by the end of this week).

**Comment by elliottower** [comment]
> Hi!
> Thanks for the reminder. We will migrate to gymnasium soon (possibly by the end of this week).

Great, thanks! If you update any training scripts feel free to let me know here as well, as we are trying to compile a list of example scripts using various RL training libraries.

**Comment by axelbr** [comment]
Hi, we have completed the migration to gymnasium. I will close this now, if further questions arise feel free to reopen.
