### ISSUE TITLE
Feature reuqest: update PettingZoo version

### ISSUE THREAD

**Issue by elliottower** [axelbr/racecar_gym#13]
Hi, would it be possible to update this repo to use the most recent version of PettingZoo? This project is listed in PettingZoo's [third-party-environments](https://pettingzoo.farama.org/environments/third_party_envs/), but we only want to include environments which work with the current version. 

If you need any help working out issues due to different versions feel free to ask, there were some breaking changes in version 1.2, so it requires a bit of code changes to adapt. The previous API returned `done` in the step() function, whereas the new one returns truncated and terminated (matching gymnasium). There is a migration guide for gymnasium explaining the changes further, the steps should be basically the same (we're working on making resources for updating old PettingZoo repositories as well): https://gymnasium.farama.org/content/migration-guide/

**Comment by axelbr** [comment]
Hi, thanks for raising this issue. We updated the env to the newest pz version.

**Comment by elliottower** [comment]
> Hi, thanks for raising this issue. We updated the env to the newest pz version.

Hi, apologies for the bad timing but there’s currently a API bug which warrants a new release, I’ll post here when it is fixed but you will want to move to that version instead. Edit: the most recent 1.22.4 release was yanked, 1.22.3 is stable so can be used.

**Comment by elliottower** [comment]
@axelbr Hey sorry for the confusion but the version 1.22.4 which you have in the requirements.txt was removed from pypi due to some API bugs, we're working on 1.23 and should get that out relatively soon but for now you should change it to 1.22.3.
