### ISSUE TITLE
change the friction parameters

### ISSUE THREAD

**Issue by AlexanderMarston05** [axelbr/racecar_gym#17]
Hi，thank you for your outstanding work! I would like to know how to change the friction parameters to enable model testing at different friction parameters.

**Comment by axelbr** [comment]
Hi!
You can try out different friction coefficents by changing the values in the URDF file: https://github.com/axelbr/racecar_gym/blob/70496767d80397010ac9b5ba722647ca67e3f85c/models/vehicles/racecar/racecar.urdf#L68-L73
