### ISSUE TITLE
How to build a custom map?

### ISSUE THREAD

**Issue by Zhong-Zi-Zeng** [axelbr/racecar_gym#18]
Hello, I have a question about building a custom map. Is it possible to achieve it? If it can, could you release some tutorials? Thanks!

**Comment by axelbr** [comment]
Hey, yes this is totally possible. Have a look at the map directory to get an overview of the files that are necessary. The maps are created by elevating occupancy gridmaps to corridors in blender. We created a [helper script](https://github.com/CPS-TUWien/f1tenth_maps/blob/master/helpers/blendermap.py) for that. The progress maps can be generated with [this script](https://github.com/CPS-TUWien/f1tenth_maps/blob/master/costmaps/generate-costmap.py).

Sorry, but I do not have time for creating such a tutorial. But I am happy to accept pull requests if you are motivated to share your notes/experiences while working on that.

**Comment by Zhong-Zi-Zeng** [comment]
am very appreciative of your feedback, I will try the method that you mentioned above.

**Comment by axelbr** [comment]
Closing it for now. Feel free to reopen if you have further questions.
